---
title: Quarto Computations
format: 
  html: 
    code-fold: true
echo: false
fig-height: 3.5
fig-width: 6
---

This dataset contains a subset of the fuel economy data from the EPA.

```{r}
#| label: load-packages
library(ggplot2)
```

@fig-scatterplot shows a positive, strong, and linear relationship between the city and highway mileage of these cars.
Additionally, mileage is higher for cars with fewer cylinders.

```{r}
#| label: fig-scatterplot
#| fig-width: 6
#| fig-height: 3.5
#| echo: true
#| code-fold: true
#| code-line-numbers: true
#| fig-cap: City and highway mileage for 38 popular models of cars.
#| fig-alt: Scatterplot of city vs. highway mileage for cars, where points are colored by the number of cylinders. The plot displays a positive, linear, and strong relationsship between city and highway mileage, and mileage increase as the number of cylinders decrease.
ggplot(mpg, aes(x = hwy, y = cty, color = cyl)) +
  geom_point(alpha = 0.5, size = 2) +
  scale_color_viridis_c() +
  theme_bw()
```

```{r}
#| echo: true
#| label: nobs
#| code-fold: true  
# nrow(mpg)
``` 

There is `{r} nrow(mpg)` observations in our data